/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#832600",
        "on-surface": "#0b1c30",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b3c5ff",
        "primary-fixed": "#dae1ff",
        "on-primary-container": "#f8f7ff",
        "outline-variant": "#c2c6d8",
        "tertiary-container": "#cc4204",
        "border-subtle": "#E2E8F0",
        "primary": "#0050cb",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-gray": "#F8FAFC",
        "surface-variant": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006e2a",
        "secondary-container": "#5cfd80",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
        "accent-yellow": "#FFB700",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#00531e",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#b3c5ff",
        "surface-container-high": "#dce9ff",
        "booking-blue": "#003580",
        "tertiary-fixed": "#ffdbd0",
        "outline": "#727687",
        "surface": "#f8f9ff",
        "secondary-fixed": "#69ff87",
        "secondary-fixed-dim": "#3ce36a",
        "on-primary-fixed": "#001849",
        "tertiary-fixed-dim": "#ffb59d",
        "on-secondary-container": "#00732c",
        "background": "#f8f9ff",
        "on-primary-fixed-variant": "#003fa4",
        "primary-container": "#0066ff",
        "on-surface-variant": "#424656",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "tertiary": "#a33200",
        "on-tertiary-fixed": "#390c00",
        "on-background": "#0b1c30",
        "error-container": "#ffdad6",
        "surface-tint": "#0054d6",
        "on-tertiary-container": "#fff6f4",
        "inverse-surface": "#213145",
        "on-secondary-fixed": "#002108",
        "surface-bright": "#f8f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "unit": "8px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
