-- Expand package and event tables with real application fields.

ALTER TABLE "TravelPackage"
  ADD COLUMN "title" TEXT NOT NULL DEFAULT 'Untitled Package',
  ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "type" TEXT NOT NULL DEFAULT 'Adventure',
  ADD COLUMN "lodging" TEXT NOT NULL DEFAULT 'Hotel',
  ADD COLUMN "price" DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN "duration" INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN "image" TEXT,
  ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "difficulty" TEXT NOT NULL DEFAULT 'Easy',
  ADD COLUMN "groupSize" TEXT NOT NULL DEFAULT 'Max 10',
  ADD COLUMN "language" TEXT NOT NULL DEFAULT 'English',
  ADD COLUMN "rating" DECIMAL(3, 2) NOT NULL DEFAULT 0,
  ADD COLUMN "reviewsCount" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "itinerary" JSONB,
  ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Event"
  ADD COLUMN "title" TEXT NOT NULL DEFAULT 'Untitled Event',
  ADD COLUMN "description" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "category" TEXT NOT NULL DEFAULT 'General',
  ADD COLUMN "price" DECIMAL(10, 2) NOT NULL DEFAULT 0,
  ADD COLUMN "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "image" TEXT,
  ADD COLUMN "organizer" TEXT,
  ADD COLUMN "featured" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
