-- TravelMate PostgreSQL DDL

CREATE TYPE "RoleName" AS ENUM ('SUPER_ADMIN', 'EVENT_PLANNER', 'TRAVELER');
CREATE TYPE "CompanyStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

CREATE TABLE "Role" (
  "id" SERIAL PRIMARY KEY,
  "name" "RoleName" UNIQUE NOT NULL
);

CREATE TABLE "User" (
  "id" SERIAL PRIMARY KEY,
  "name" TEXT NOT NULL,
  "email" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "roleId" INTEGER NOT NULL REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "companyId" INTEGER,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Company" (
  "id" SERIAL PRIMARY KEY,
  "companyName" TEXT NOT NULL,
  "businessEmail" TEXT UNIQUE NOT NULL,
  "phone" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "logo" TEXT,
  "licenseDocument" TEXT,
  "status" "CompanyStatus" NOT NULL DEFAULT 'PENDING',
  "ownerId" INTEGER UNIQUE NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

ALTER TABLE "User"
  ADD CONSTRAINT "User_companyId_fkey"
  FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE "TravelPackage" (
  "id" SERIAL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "location" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "lodging" TEXT NOT NULL,
  "price" DECIMAL(10, 2) NOT NULL,
  "duration" INTEGER NOT NULL,
  "image" TEXT,
  "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "difficulty" TEXT NOT NULL DEFAULT 'Easy',
  "groupSize" TEXT NOT NULL DEFAULT 'Max 10',
  "language" TEXT NOT NULL DEFAULT 'English',
  "rating" DECIMAL(3, 2) NOT NULL DEFAULT 0,
  "reviewsCount" INTEGER NOT NULL DEFAULT 0,
  "itinerary" JSONB,
  "companyId" INTEGER NOT NULL REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

CREATE TABLE "Event" (
  "id" SERIAL PRIMARY KEY,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "price" DECIMAL(10, 2) NOT NULL,
  "date" TIMESTAMP(3) NOT NULL,
  "location" TEXT NOT NULL,
  "image" TEXT,
  "organizer" TEXT,
  "featured" BOOLEAN NOT NULL DEFAULT false,
  "companyId" INTEGER NOT NULL REFERENCES "Company"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL
);

INSERT INTO "Role" ("name") VALUES
  ('SUPER_ADMIN'),
  ('EVENT_PLANNER'),
  ('TRAVELER')
ON CONFLICT ("name") DO NOTHING;
